### ISSUE TITLE
Access to sources without login

### ISSUE THREAD

**Issue by JaniDJ** [gogs/gogs#4742] opened 2017-09-02 12:36 UTC
- Gogs version (or commit ref): b1100b5e345a8a6f5e3f3dfd19e18c9cc8b499e8
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description

Hey there, I configured Gogs so that you need to login in order to access the repos. But with the help of the explore tab you can see and access anything. I think that's not right :). Maybe I have done something wrong?

Jani

Config:
![cfg1](https://user-images.githubusercontent.com/5995845/29995547-f7f3ed58-8feb-11e7-8a64-c3adeafeffe1.PNG)

Expolore Tab:
![cfg2](https://user-images.githubusercontent.com/5995845/29995546-f7f3b3b0-8feb-11e7-974f-07116132444b.PNG)

Visible Things:
![cfg3](https://user-images.githubusercontent.com/5995845/29995545-f7f3c77e-8feb-11e7-8d05-28018bfe81a9.PNG)

**Comment by jaydio** [comment] 2017-09-20 09:41
Duplicate of https://github.com/gogits/gogs/issues/3744.

**Comment by Unknwon** [comment] 2018-11-26 12:17
For some reason, you need to restart your Gogs to make this signin require option to work. :pensive:

**Closed by Unknwon** 2018-11-26 12:17 UTC
