### ISSUE TITLE
500: An error has occurred : get submodule "tcpdf": revision does not exist

### ISSUE THREAD

**Issue by ELForcer** [gogs/gogs#6436] opened 2020-12-02 07:39 UTC
An update was made from version 0.11.91 to version 0.12.3 according to the instructions: https://gogs.io/docs/upgrade/upgrade_from_binary
After committing, it is not possible to view the contents of the repository through the web interface.
Old repositories open fine.

Application Version: 0.12.3
git version 2.20.1
OS: Debian GNU/Linux 10 (buster)

_Originally posted by @ELForcer in https://github.com/gogs/gogs/issues/6007#issuecomment-737048206_

**Comment by unknwon** [comment] 2020-12-02 11:40
Thanks for the feedback!

How can I reproduce?

**Comment by ELForcer** [comment] 2020-12-02 11:53
I got it like this:
1. Downloaded update 0.12.3
2. Turned off the web server
3. Moved the folders from the old gogs directory to the new
4. Enabled the web server
** The site is up, the contents of the repository opens **
5. Made git commit and git push
6. I go to the web server
** The site is working, the contents of the repository to which the push was made DO NOT open. Error 500. **
The rest of the repositories on the same site are opened.

Moved content to old version 0.11.91.
Content started to open again on old version after git push.

**Comment by unknwon** [comment] 2020-12-02 12:59
Can you provide a sample repo that can cause 0.12.3 to 500?

**Comment by ELForcer** [comment] 2020-12-02 13:01
I will try to update my home repository to version 0.12.3 and report the results. But Linux Mint 20 is installed there, not Debian 10.

**Comment by unknwon** [comment] 2020-12-02 13:08
I appreciate your replies but I still have no idea how to reproduce the problem. I'll ask this instead, are you able to reproduce the 500 on https://try.gogs.io?

**Comment by ELForcer** [comment] 2020-12-05 18:42
I checked it on my home PC (Linux Mint 20). It was also updated to 0.12.3 and made a push. The repository opens fine. Problem only means Debian 10 or installed packages. I will look for the problem further.

**Comment by unknwon** [comment] 2020-12-05 19:17
Can you upload a sample repository to try.gogs.io and reproduce the 500?

**Comment by ELForcer** [comment] 2020-12-07 08:10
Unfortunately, I can't. This is a corporate project. The source code cannot be posted on the Internet. And I do not think that this is the case in the project code.

But I can lay out the project structure:
![Снимок экрана от 2020-12-07 12-02-52](https://user-images.githubusercontent.com/30798063/101325131-afba6900-3884-11eb-99c9-1504a12f336e.png)

The last commit was added to the following line in .gitignore:
![Снимок экрана от 2020-12-07 11-59-51](https://user-images.githubusercontent.com/30798063/101325009-81d52480-3884-11eb-8c78-3498b303e6ab.png)

Сommit 90311bb706 contains the following change:
![Снимок экрана от 2020-12-07 12-03-09](https://user-images.githubusercontent.com/30798063/101325145-b517b380-3884-11eb-89d7-08207ffb92c2.png)

I can't go to the tspdf folder on the site.
Besides the master branch, there are no others.

**Comment by unknwon** [comment] 2020-12-13 01:53
@ELForcer Thanks! So when does the 500 happen exactly? When you click on the following?

<img width="145" alt="CleanShot 2020-12-13 at 09 53 20@2x" src="https://user-images.githubusercontent.com/2946214/102001099-0b736f00-3d29-11eb-87a3-d4979f9a8d9e.png">

**Comment by ELForcer** [comment] 2020-12-13 08:51
I recorded a video where you can see that the repository works on the old version and does not work after the update:
https://yadi.sk/i/1W2H5uYHQMuL2w

**Comment by assist726** [comment] 2021-01-20 07:39
Have the same issue here, but only on specific branches of the repo. I assume certain styles of commit histories break the system ?

**Comment by mg64ve** [comment] 2021-02-28 08:10
I have same issue in a n home project:

`An error has occurred : get submodule "tensorflow": revision does not exist`

git push and clone works apparently.
Any update on that?

**Comment by Demon1110** [comment] 2021-05-25 09:26
![image](https://user-images.githubusercontent.com/9859323/119473904-35bc6480-bd7e-11eb-9174-8d64651a9cd5.png)
help me ,I have same issue 
How to solve this problem

**Comment by ELForcer** [comment] 2021-05-25 11:29
Workaround, use the old version (0.11). But her mail notification does not work, at least for me.

**Comment by xingxing122** [comment] 2021-06-07 12:55
How did you solve this problem in the endHow did you solve this problem in the end

**Comment by lowking** [comment] 2021-06-22 03:44
![image](https://user-images.githubusercontent.com/33308659/122859603-da669d80-d34e-11eb-9853-f018bd649128.png)
help me ,I have same issue
How to solve this problem

I just created a repository and pushed
```
git init
git add *
git commit -m 'init'
git push
```

**Comment by ELForcer** [comment] 2021-06-22 04:15
Use the old version (0.11). There is no such problem with submodule revisions, but notifications may not work.

**Comment by ELForcer** [comment] 2022-03-14 06:41
On version 0.12.5 problem exists.

![image](https://user-images.githubusercontent.com/30798063/158118167-c30871a3-4b12-4fe1-a612-b68617a286d3.png)

An error has occurred : get submodule "tcpdf": revision does not exist
Application Version: 0.12.5

However, the repository now opens without errors.
(I don’t know if this is the merit of Gogs or the owner of the current repository)
The problem only now remained in the old commit.

**Comment by hellorayza** [comment] 2022-04-24 06:29
My colleague had this problem too.
Accoding to his description, he upload needless  `.git`  folder in second level folder. 
Maybe the outer(the root directory) `.git`  folder was breakdown  also or his used wrong git command.

**Comment by homealim2012** [comment] 2022-04-28 09:37
在根目录下添加.gitmodules
里面添加如下内容
[submodule "your_submodule_name"]
        path = your_submodule_name
        url = https://github.com/homealim2012/gcr.io_mirror
commit并push即可

**Comment by unknwon** [comment] 2022-06-25 11:35
> My colleague had this problem too.
> Accoding to his description, he upload needless `.git` folder in second level folder.
> Maybe the outer(the root directory) `.git` folder was breakdown also or his used wrong git command.

I've successfully reproduced the behavior using this, looking into fix soon 🕵️

**Comment by DingGuodong** [comment] 2022-07-13 08:11
> 在根目录下添加.gitmodules 里面添加如下内容 [submodule "your_submodule_name"] path = your_submodule_name url = https://github.com/homealim2012/gcr.io_mirror.git commit并push即可

This is a solution which I tested and passed.

**Comment by esayre-um** [comment] 2022-08-24 16:26
@unknwon since you added this issue to the 0.12.11 milestone, does that mean it is still not resolved in 0.12.10?

I'm having this issue on my local gogs install, but was unable to reproduce using try.gogs.io.

**Comment by swedan333** [comment] 2022-11-11 11:12
![image](https://user-images.githubusercontent.com/22683615/201328642-38d1d069-aece-4d75-bd43-b17f3a1f101a.png)
version 0.13.0 dev running in a docker container
is there a solution or workaround for this

**Comment by fastchain** [comment] 2023-01-07 06:08
It looks it happens when  gogs can't resolve origins from other repositories. I had the same issue with openssl folder in my project and I fixed it this way

1. ```git remote remove origin``` (in openssl folder)
2. create openssl repo in gogs
3. ```git remote add origin http://[gogs_host]/[gogs_user]/openssl.git ```
4. ```git push -u origin master```

How I have openssl in gogs, gogs can resolve the submodule and  I don't see the error message any more.

**Comment by al-heisner** [comment] 2023-01-09 16:12
I have run into and was able to reproduce exact same error
1. create new repository in gogs
2. create another new repo in gogs (or github, etc)
3. git clone repo#1
4. within repo#1, git clone repo#2
5. git add --all && git commit && git push
6. 500 error when visiting repo#1 in gogs web UI

adding .gitmodules with repo#2 details into repo#1 removes the 500 error in this case

**Comment by windhamdavid** [comment] 2023-02-11 21:27
gogs.log - 2023/02/11 16:18:05 [ERROR] [...gogs/internal/route/repo/view.go:57 renderDirectory()] get commits info: get submodule "wp": revision does not exist.  -> gogs v0.12.9 git v2.34.1 go1.18.1 -> just related to submodules... best of luck on the fix. Thank you for your effort ✌🏼

**Comment by unknwon** [comment] 2023-02-14 05:49
> I have run into and was able to reproduce exact same error
> 
> 1. create new repository in gogs
> 2. create another new repo in gogs (or github, etc)
> 3. git clone repo#1
> 4. within repo#1, git clone repo#2
> 5. git add --all && git commit && git push
> 6. 500 error when visiting repo#1 in gogs web UI
> 
> adding .gitmodules with repo#2 details into repo#1 removes the 500 error in this case

Thank you @al-heisner! I successfully reproduced with these steps ❤️ 

On the surface looks like this happens when there is for whatever reason an undeclared submodule in the repository, will update Gogs to be more lenient about this.

**Comment by unknwon** [comment] 2023-02-14 06:47
The patch has landed in 0.13.0+dev, and will be back-ported to 0.12.11 (no ETA).

**Closed** 2023-02-14 06:46 UTC
Labels: 💊 bug

**Comment by esayre-um** [comment] 2023-02-14 14:47
Great to hear… I too was having trouble reproducing this on this test server… curiously my repos _seem_ to have the correct info in .gitmodules but still were giving me 500 errors.

**Comment by unknwon** [comment] 2023-02-25 08:02
The 0.12.11 has been released that includes the patch of the reported issue.

**Comment by windhamdavid** [comment] 2023-02-25 12:15
Thank you 👊🏼 updated to v0.12.11 and can confirm it fixes this issue.
