### ISSUE TITLE
Broken LDAP Auth

### ISSUE THREAD

**Issue by Jacox98** [gogs/gogs#6074] opened 2020-04-06 15:41 UTC
**Describe the bug**
Hello,
I noticed a problem with the configuration and use of the LDAP server.
When trying to edit or add a method the server responds with the following error
An error has occurred: sql: Scan error on column index 5, name "cfg": unsupported Scan, storing driver.Value type [] uint8 into type * core.Conversion

The fact is highly blocking because it makes the platform unusable, nobody can authenticate themselves in LDAP

**Gogs version or commit**
gogs/gogs:latest

**Operating system**
Docker

**Database**
mariadb:latest

**To Reproduce**
Simple login in LDAP
or
Administration panel
authentication
Try to modify one of the servers
Crash

**Expected behavior**
Login

**Actual behavior**
Unable to login or edit auth method

**Screenshots**
![image](https://user-images.githubusercontent.com/35966887/78577058-cc059200-782d-11ea-948a-879e466554de.png)

**Comment by unknwon** [comment] 2020-04-06 15:54
Thanks for the feedback! I've reproduced on my dev machine, working on fix now.

**Comment by unknwon** [comment] 2020-04-06 16:29
Patch has been merged to `master`, please wait for ~20mins for Docker Hub to finish building the new image.

**Closed** 2020-04-06 16:29 UTC
Labels: 💊bug

**Comment by Jacox98** [comment] 2020-04-07 07:03
> Patch has been merged to `master`, please wait for ~20mins for Docker Hub to finish building the new image.

Hi thanks for the quick fix, but I seem that the image is always broken even by downloading it again from the docker hub

**Comment by unknwon** [comment] 2020-04-07 07:12
Hmm... which image version have you pulled to your local machine?

**Comment by unknwon** [comment] 2020-04-07 07:15
OK, looks like Docker Hub has been failing to build image since yesterday, let me see what's going on.

**Comment by unknwon** [comment] 2020-04-07 09:29
Docker Hub seems taking forever to build an image :(

**Comment by Jacox98** [comment] 2020-04-07 10:33
> Docker Hub seems taking forever to build an image :(

Ouroboros has updated the container now everything works thanks a lot.
Good day
