### ISSUE TITLE
API error list-issues-for-a-repository for PostgreSQL

### ISSUE THREAD

**Issue by qihangnet** [gogs/gogs#4543] opened 2017-06-01 03:19 UTC
- Gogs version (or commit ref): 0.11.6.0407
- Git version: 
- Operating system:  docker of gogs/gogs
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant

## Description

API: `api/v1/repos/:owner/:repo/issues`
Response:

```
{
  "message": "pq: column \"issue.created_unix\" must appear in the GROUP BY clause or be used in an aggregate function",
  "url": "https://github.com/gogits/go-gogs-client/wiki"
}

```

**Comment by raphink** [comment] 2017-08-18 13:29
I confirm that bug on Gogs on 0.11.4. This is a very blocking bug as it prevents from listing issues with the API.

**Comment by mckaygerhard** [comment] 2017-09-01 17:12
related to #4648  postgres issue due the SQL made are done like if MYSQL was the only DB in the world! maybe reproducible with sqlite too!

SQL ANSI standar define that when agroup realted all the collumns must be, to avoid subquerys can be made but hit performance

**Comment by mckaygerhard** [comment] 2018-11-26 13:39
it's a consecuence of using mysql/mssql DBMS.. and not a good DBMS like postgres.. the group byare too flesyble in those

**Comment by Unknwon** [comment] 2018-11-28 15:30
Hi, I'm using PostgreSQL 11 and Gogs 0.11.70, not able to reproduce this error. Have you all are using the latest version?

**Comment by mckaygerhard** [comment] 2018-11-28 15:41
use postgres 9.X or 10, that are valid and good performance (due less features) due postgres 11 now permit having flexible sentences and in any cases its a breack in ANSI SQL standards: see https://blog.jooq.org/2018/07/05/postgresql-11s-support-for-sql-standard-groups-and-exclude-window-function-clauses/

**Comment by Unknwon** [comment] 2018-11-28 15:52
I reinstalled 9.6 version still not getting the error while calling this API endpoint...

**Comment by Unknwon** [comment] 2018-11-28 15:57
I check the relevant source code which hasn't been changed since 0.11.4. I think there might be a special case of data to trigger this error, as I'm setting up as new with only one issue in the repository.

https://github.com/gogs/gogs/blob/e9be8016e6b87efbc3bc62b373bed9143c2bac74/models/issue.go#L883-L948

**Comment by mckaygerhard** [comment] 2018-11-28 18:22
i recheck the postgres 11 features, puff i spent time installing a linux to try and the GROUP BY does not allow that, so the case to trigger this error are very very special..

**Comment by Unknwon** [comment] 2018-11-28 20:42
The underlying function calls are same for API and the web UI, which means the issue tracker UI wouldn't be able to load when you visit your `/username/reponame/issues`, is that the case?

**Comment by mckaygerhard** [comment] 2018-11-28 21:07
umm must be ! but now i nothed no response from issue authors , in any case i'm very interesting in this case! i not have that version in specific, i can try to reprouce the issue but right now not! i suggested to verify the generated querys.. that's why i hate the mysql/mssql due causes many developers breaks standars

**Comment by Unknwon** [comment] 2018-11-28 21:11
The more magic thing to me, is that the query does not even have GROUP BY, why would the DB complains about this...?

**Comment by Unknwon** [comment] 2018-12-10 23:42
I'm closing this until someone can reproduce this with Gogs version higher than 0.11.66.

**Closed by Unknwon** 2018-12-10 23:42 UTC
Labels: kind/bug, status/needs feedback, status/needs reproduce
