### ISSUE TITLE
Unable to resolve submodule with relative URL

### ISSUE THREAD

**Issue by frosteyes** [gogs/gogs#6319] opened 2020-09-09 13:33 UTC
Having a url like 

https://gogs.server.com/org/repo1.git

This has a .gitmodules files with

```
[submodule "testsub"]
	path = testsub
	url = ../repo2.git
```

for accessing https://gogs.server.com/org/repo2.git

It works when you checkout the archive. But the link from the webinterface on https://gogs.server.com/org/repo1 points to https://gogs.server.com/repo2

The issue has previously been present  - closed with fixed. 
https://github.com/gogs/gogs/issues/1926

This is not the case anymore.

The build information.

Build Information
Application version 0.12.1
Git version 2.24.3
Go version go1.14.7
Build time 2020-08-27 06:59:23 UTC
Build commit43fc8260850090b55d4ee2586a819b3b6c016279

**Comment by unknwon** [comment] 2020-09-09 14:00
I _think_ the solution is to update this function:

https://github.com/gogs/gogs/blob/594a2dc41f6e70f0cc535b125316d05e12666fda/internal/gitutil/submodule.go#L20

**Comment by frosteyes** [comment] 2020-09-09 14:02
@unknwon agree - this is the place to fix it.

**Comment by unknwon** [comment] 2020-09-18 07:54
Turns out the root cause is that the browser doesn't like the path `../repo2` (returned by `InferSubmoduleURL`). Nevertheless, fixed in https://github.com/gogs/gogs/pull/6337.

**Comment by unknwon** [comment] 2020-09-18 08:19
The patch will be included in the next patch release: 0.12.2.

**Closed** 2020-09-18 08:19 UTC
Labels: 💊 bug, 🔙 regression

**Comment by frosteyes** [comment] 2020-09-18 08:45
Thanks for this!! Super cool that you fixed it so fast.
