### ISSUE TITLE
Can't open `https://try.gogs.io`

### ISSUE THREAD

**Issue by ChristmasZCY** [gogs/gogs#7772] opened 2024-07-04 09:21 UTC
### What needs to be improved? Please describe

Can't open `https://try.gogs.io`, I want to try gigs

### Why do you think it is important?

Because it's try website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZD-FLoM** [comment] 2024-07-04 13:42
The CN targets dev.epic****app.com instead of try.gogs.io or gogs.io. A new certificate should be issued with the proper CN.

**Comment by ChristmasZCY** [comment] 2024-07-05 01:43
> The CN targets dev.epic****app.com instead of try.gogs.io or gogs.io. A new certificate should be issued with the proper CN. 

Sorry，what's exactly website url?

**Comment by ZD-FLoM** [comment] 2024-07-05 03:38
> > The CN targets dev.epic****app.com instead of try.gogs.io or gogs.io. A new certificate should be issued with the proper CN.
> 
> Sorry，what's exactly website url?

You can view the certificate information and the full URL by clicking on the icon next to the URL in the browser. Since the domain in the Common Name of the certificate is different than the actual URL, browsers see this as malicious. It could just be a mistake by the domain owner.

**Comment by ChristmasZCY** [comment] 2024-07-05 04:32
> > > The CN targets dev.epic****app.com instead of try.gogs.io or gogs.io. A new certificate should be issued with the proper CN.
> 
> > 
> 
> > Sorry，what's exactly website url?
> 
> 
> 
> You can view the certificate information and the full URL by clicking on the icon next to the URL in the browser. Since the domain in the Common Name of the certificate is different than the actual URL, browsers see this as malicious. It could just be a mistake by the domain owner. 

`dev.epicparkapp.com` is not OK either.

**Comment by privong** [comment] 2024-07-16 20:27
Duplicate of #7651?

**Comment by ChristmasZCY** [comment] 2024-07-17 01:28
> Duplicate of #7651?

yes

**Comment by candlerb** [comment] 2024-10-15 10:50
The certificate at try.gogs.io is currently for "adney.land"

Chrome says it uses HSTS so won't offer to click through.

So you type the hidden phrase "thisisunsafe" to get past the certificate error.

And then the web server gives a 403 error.

If this can't be fixed, I suggest removing the "Try a demo" link entirely from the Gogs homepage at https://gogs.io/

**Comment by unknwon** [comment] 2024-12-22 19:01
Hi, thanks for your feedback! We have just brought back https://try.gogs.io recently!

**Closed by unknwon** 2024-12-22 19:01 UTC
Labels: 📖 documentation

**Comment by ChristmasZCY** [comment] 2024-12-23 02:11
> Hi, thanks for your feedback! We have just brought back https://try.gogs.io recently!您好，感谢您的反馈！我们最近刚刚带回了 https://try.gogs.io！

Thank you!
