### ISSUE TITLE
"pre-receive hook declined" after running Gogs for some time on Windows

### ISSUE THREAD

**Issue by ZantsuRocks** [gogs/gogs#6316] opened 2020-09-08 12:51 UTC
**Describe the bug**
When trying to push some repo to Gogs it throws an error 

**Gogs version and commit**
0.12.1 - 43fc8260850090b55d4ee2586a819b3b6c016279 _(The bug never occurred on 0.11.91)_

**Git version**
git version 2.23.0.windows.1 (Windows Client and Windows Server)
and
git version 2.17.1 (Linux Client)

**Operating system**
Pushing PC -> Windows 10, Linux
Repo Server -> Windows Server 2016

**Database**
SQLite3

**To Reproduce**
1. Open Gogs Service in services.msc `"C:\gogs\gogs.exe" web --config "C:\gogs\custom\conf\app.ini"`
2. Push some data (Push completes)
3. Let the service run for about 24h
4. Try to push some data again (Push throw an error)
```
git: 'credential-cache' is not a git command. See 'git --help'.
remote: Gogs: Internal error        
To https://srvfs01.agst.com.br:3000/AGST/JigaBrise.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://srvfs01.agst.com.br:3000/AGST/JigaBrise.git'
```
5. Restart the service on services.msc
6. Try to push again and it works.

**Can you reproduce the bug at https://try.gogs.io?**
No

**Expected behavior**
As there is no pre-receive hook on the repo or something wrong in the local repo to finish the push successfully

**Actual behavior**
When trying to push some repo to Gogs it throws an error

**Screenshots**
Error:
![erro](https://user-images.githubusercontent.com/9502836/92476412-48254c80-f1b5-11ea-8b70-6b4c5bfc8733.png)
Ok (After restarting the service):
![ok](https://user-images.githubusercontent.com/9502836/92476430-51161e00-f1b5-11ea-9a65-639d44d255e7.png)

**Additional context**
[app.ini.txt](https://github.com/gogs/gogs/files/5188290/app.ini.txt)
[gogs.log](https://github.com/gogs/gogs/files/5188257/gogs.log)
hooks/*.log are empty

**Comment by Crayon2000** [comment] 2020-09-08 15:10
I am currently having the same problem. I need to restart the service each day in order to make push request work. The problem did not occur before updating to 0.12.1. I am also using gogs on Windows.

**Comment by unknwon** [comment] 2020-09-09 06:30
Thanks for reporting! 

I don't have any clue about the root cause top of my head, but I'll take a look during 0.13 dev cycle.

**Comment by jmk92** [comment] 2020-09-17 14:54
With the same problem, I even tried to restart the service regularly, and I have rolled back to 0.11.91

**Comment by unknwon** [comment] 2020-09-18 09:16
My current guess is that the daily log rotation has problem on Windows, since it seems to often appear in the next day? 🤔

**Comment by jmk92** [comment] 2020-09-18 12:07
@unknwon Maybe, I always thought it was more than 10 hours. When there is a problem, my method is to restart the gogs service every time to solve the problem. After encountering this problem, I tried a lot, including changing different versions of GIT, re covering and installing new ones. All of these problems could not be solved. I manually restart every day for more than 20 days, but I didn't wait for your repair version. I gave up and went back to 0.11

**Comment by MooLee89** [comment] 2020-09-26 04:21
This problem is very serious, it reappeared after restarting for 12 hours

**Comment by jmk92** [comment] 2020-09-26 05:54
@MooLee89 It's very serious. Every day I restart, I want to write an auxiliary program to help gogs restart automatically. The author hasn't found the reason yet, so I suggest to use the old version. There are more and more users who upgrade to the new version. As long as they use windows, they will encounter this problem. Now, there are 4 or 5 people who are fed back. In fact, hundreds of people may have encountered this problem. Please wait for version 0.13 to be funny,because it could take a year.

**Comment by unknwon** [comment] 2020-09-26 10:21
I've set up a 0.13.0+dev on a Windows server see if I can reproduce this problem after few hours.

**Comment by unknwon** [comment] 2020-09-28 05:17
Found the cause (by setting `RUN_MODE=dev`): The data race on `xorm.log` file during daily rotation.

```
remote: Failed to set database engine: create 'xorm.log': init: init rotation: rename rotate file: 
rename C:/Users/Administrator/Desktop/gogs/log/xorm.log C:/Users/Administrator/Desktop/gogs/log/xorm.log.2020-09-26: 
The process cannot access the file because it is being used by another process.
```

Working on a fix.

**Comment by unknwon** [comment] 2020-09-29 14:26
The patch will be included in 0.12.3.

**Closed** 2020-09-29 14:26 UTC
Labels: 💊 bug, 🔙 regression, 🧗🏾 windows

**Comment by unknwon** [comment] 2020-10-07 16:20
The 0.12.3 has been released.

**Comment by jmk92** [comment] 2020-10-07 16:49
Thank you very much. I often check whether 0.12.3 has been released these days. Last night, I saw that it was released 17 minutes ago, but there was only the source code. I waited for an hour and kept refreshing. At 0:17, I finally got the Windows version.
