### ISSUE TITLE
When Branchname contains number sign (#), can't view older commits

### ISSUE THREAD

**Issue by danowar2k** [gogs/gogs#4685] opened 2017-08-10 12:46 UTC
- Gogs version (or commit ref): 0.11.28.0718
- Git version: Unknown (I'm not the admin)
- Operating system: 
(Server) unknown (I'm not the admin)
(Client) Windows 7, Firefox 54.0.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
Unknown (I'm not the admin)
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes (https://try.gogs.io/danowar/bug-older-commits/commits/%23001-Testbranch)
- Log gist (usually found in `log/gogs.log`):
- None (I'm not the Admin)
## Description
When you go to the commits page of a branch with a name containing a number sign, the links at the bottom ("Older", "Newer") are not escaped in the right way. The number sign is not escaped.

I'm not aware of any other unescaped chars in branch names, but that doesn't mean there aren't any.

**Comment by alexanderadam** [comment] 2017-11-14 10:25
I'm not a maintainer here but this is most probably a duplicate of #4601 right?

PS: Why do you have a `#` in branch names?

**Comment by danowar2k** [comment] 2017-11-14 11:50
Hi,
the branch name contains the issue nr. The # is the indicator for "the
numbers after this represent an issue nr."

Regards,
Daniel

Am 14.11.2017 11:26 vorm. schrieb "Alexander Adam" <notifications@github.com

**Comment by alexanderadam** [comment] 2017-11-14 14:33
Yes I see. It's a duplicate nevertheless, right? 😉

**Comment by danowar2k** [comment] 2017-11-14 14:41
I'd argue that I've described my issue using (hopefully) more understandable grammar and spelling, but yes, it seems to be a similar. However, my issue was wrongly escaped links. His seems to be something regarding pull requests. It may be the same cause, but another viewpoint...?

**Closed** 2024-09-14 13:28 UTC
Labels: 💊 bug, 💻 ui
