### ISSUE TITLE
SSH keys not automatically added to the authorized_keys file

### ISSUE THREAD

**Issue by linkdd** [gogs/gogs#4751] opened 2017-09-04 12:07 UTC
- Gogs version (or commit ref): 0.11.29.0727
- Git version: 2.11.3
- Operating system: alpine (docker image) 
- Database :
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): Not relevant

## Description

When I add an SSH key to a user, or a repository (as deployment key), the key is not added to ``/data/git/.ssh/authorized_keys``.

The current workaround is to go to the admin dashboard, and execute the rewriting of SSH keys manually.

**Comment by Fastidious** [comment] 2017-09-04 16:08
Same as #4435.

**Comment by linkdd** [comment] 2017-09-04 16:12
Hello,

This is not really the same. In the issue you are quoting, it is a feature request to regenerate the ``authorized_keys`` at gogs start.

Here is a bug report about the ``authorized_keys`` not being updated automatically when a key is added via the web interface.

**Comment by Fastidious** [comment] 2017-09-04 16:28
@linkdd have you tried stopping and starting `gogs`, to see if the keys get written? I think they are related, #4435 requests an automatic execution of the rewriting keys.

**Comment by linkdd** [comment] 2017-09-04 16:32
I tried, and it didn't work.

I should also say that this is not a viable solution. I should not be restarting gogs, or manually trigger the rewriting each time one of my user adds a key.

The server is not in a production environment yet, and I won't have many users, so this is not an urgent issue.

**Comment by jtktam** [comment] 2018-03-09 14:55
I am running into the same issue when the user adds a key via their settings, the key doesn't get added to the authorized_keys file and I have to manually trigger the regen from the admin screen

it is not a big deal right now for my small team but I can see how this can be an issue for big teams

**Comment by Unknwon** [comment] 2018-04-21 21:39
I'm closing this if you can't reproduce on demo site.

**Comment by rsurgiewicz** [comment] 2020-09-08 22:17
Hi folks,
Running 0.12.1 and I'm still facing the issue.
After adding ssh key via web interface it does not appear on .ssh/authorized_keys automatically.

However some black magic happens because after some time (1h I guess) authorized_keys are regenerated?
How can I regenerate it manually?

Which logs / data shall I deliver to help You investigate the issue

**Comment by unknwon** [comment] 2020-09-09 01:17
@rsurgiewicz You can regenerate on admin dashboard `/admin`.

<img width="747" alt="Screen Shot 2020-09-09 at 9 17 06 AM" src="https://user-images.githubusercontent.com/2946214/92543157-4757ed80-f27d-11ea-8359-9ea8032a6ab3.png">

**Comment by rsurgiewicz** [comment] 2020-09-09 05:24
Ok thanks.
Anyone know what is the schedule of "automatic `authorized_keys `rewrite" ?

Shall it be considered as a bug or it's just by design?

**Comment by unknwon** [comment] 2020-09-09 06:16
> Ok thanks.
> Anyone know what is the schedule of "automatic `authorized_keys `rewrite" ?
> 
> Shall it be considered as a bug or it's just by design?

@rsurgiewicz That happens whenever a SSH key is added/removed.

**Comment by rsurgiewicz** [comment] 2020-09-09 07:38
Ok so in this case it does not happen. At least in my instance.
Manual force rewrite is a workaround

**Comment by linkdd** [comment] 2020-09-09 07:38
@unknown No it's not happening, that was the whole point of the issue.

And sorry but we do not have access to the file system of the demo site to verify the issue. You have the steps to reproduce it, it's not that hard.

But hey, it's been 3 years, no worries, I'm just not using gogs anymore.

**Comment by unknwon** [comment] 2020-09-09 08:49
@rsurgiewicz Just to confirm, manually run the operation on admin dashboard worked for you?

**Comment by rsurgiewicz** [comment] 2020-09-09 08:54
Yes manual trigger works

Dnia 9 września 2020 10:49:31 CEST, "ᴜɴᴋɴᴡᴏɴ" <notifications@github.com> napisał(a):

**Comment by unknwon** [comment] 2020-10-04 07:44
@rsurgiewicz Can you make sure the value of this config option is FALSE?

https://github.com/gogs/gogs/blob/cf86546dff822cfc316832ed61deaf2c28880447/conf/app.ini#L76-L77

I've set up a fresh Docker container `gogs/gogs:latest` and use SQLite3 as the database, after adding a public key, I'm able to clone a repository via SSH. Also checked new key was added to the `/data/git/.ssh/authorized_keys` (inside container) file.

**Comment by JohnYauxxx** [comment] 2020-10-04 07:55
Thank for your  cooperation

**Comment by rsurgiewicz** [comment] 2020-10-04 08:00
Hi there I actually have it enabled

```
[server]
DOMAIN           = xxx
HTTP_PORT        = 3000
ROOT_URL         = xxx
LOCAL_ROOT_URL   = http://127.0.0.1:3000
DISABLE_SSH      = false
SSH_PORT         = 10022
START_SSH_SERVER = true
OFFLINE_MODE     = false

```

**Comment by unknwon** [comment] 2020-10-04 10:57
@rsurgiewicz I see. Builtin SSH server does not read/use this file at all, it checks the public key directly against the database.

If you rely on this file to make Git clone/push via SSH work, then the builtin SSH server is in fact not used.

**Closed by unknwon** 2020-10-04 10:57 UTC
Labels: status: needs feedback, status: needs reproduce, 💊 bug

**Comment by rsurgiewicz** [comment] 2020-10-04 11:17
If it does not use the file why access via ssh os not working until the key is added to the file?

**Comment by unknwon** [comment] 2020-10-04 11:20
@rsurgiewicz I suspect you're not using the correct SSH URL, suggested reading: https://discuss.gogs.io/t/how-to-config-ssh-settings/34
